[package]
name = "josh/webool"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Networker = "leifstout/networker@0.2.1"

[server-dependencies]
ProfileService = "firebird702/profileservice@1.1.0"
